steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['install']

  # Build the application
  - name: 'node:20'
    entrypoint: 'npm'
    args: ['run', 'build']
    env:
      # Add any build-time environment variables here
      - 'NODE_ENV=production'

  # Optional: Deploy to Cloud Storage bucket (uncomment and configure as needed)
  # - name: 'gcr.io/cloud-builders/gsutil'
  #   args: ['-m', 'rsync', '-r', '-c', '-d', './dist/', 'gs://YOUR_BUCKET_NAME/']

# Artifacts to store (the built application)
artifacts:
  objects:
    location: 'gs://$PROJECT_ID-build-artifacts'
    paths:
      - 'dist/**'

# Build timeout
timeout: '600s'

# Options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
